FSWDFinalProject.UI.MVC/Controllers/ComputersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.DATA.EF;
using FSWDFinalProject.UI.MVC.Utilities;
using Microsoft.AspNet.Identity;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class ComputersController : Controller
    {
        private FinalEntities db = new FinalEntities();

        // GET: Computers
        [Authorize(Roles = "Admin, Customer, Employee")]
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            if (User.IsInRole("Customer"))
            {
            var computers = db.Computers.Where(c => c.OwnerId == currentUser).Include(c => c.UserDetail).ToList();

            return View(computers.ToList());
            }

            return View(db.Computers.ToList());

        }

        // GET: Computers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Computer computer = db.Computers.Find(id);
            if (computer == null)
            {
                return HttpNotFound();
            }
            return View(computer);
        }

        // GET: Computers/Create
        public ActionResult Create()
        {
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName");
            return View();
        }

        // POST: Computers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ComputerId,ComputerModel,OwnerId,ComputerPhoto,Notes,IsActive,DateAdded")] Computer computer, HttpPostedFileBase logo)
        {
                #region File Upload

                if (ModelState.IsValid)
                {
                    //use default img if none is provided
                    string file = "noImg.png";
                    if (logo != null)
                    {
                        file = logo.FileName;
                        string ext = file.Substring(file.LastIndexOf("."));
                        string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                        if (goodExts.Contains(ext.ToLower()) && logo.ContentLength <= 4194304)
                        {
                            file = Guid.NewGuid() + ext;

                            #region Resize Image
                            string savePath = Server.MapPath("~/Content/images/computers/");

                            Image convertedImage = Image.FromStream(logo.InputStream);

                            int maxImageSize = 500;

                            int maxThumbSize = 100;

                            ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                            #endregion
                        }
                        computer.ComputerPhoto = file;
                    }
                    #endregion
                    db.Computers.Add(computer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", computer.OwnerId);
            return View(computer);
        }

        // GET: Computers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Computer computer = db.Computers.Find(id);
            if (computer == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", computer.OwnerId);
            return View(computer);
        }

        // POST: Computers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ComputerId,ComputerModel,OwnerId,ComputerPhoto,Notes,IsActive,DateAdded")] Computer computer, HttpPostedFileBase logo)
        {
            if (ModelState.IsValid)
            {
                string file = computer.ComputerPhoto;
                #region File Upload
                if (logo != null)
                {
                    file = logo.FileName;

                    string ext = file.Substring(file.LastIndexOf('.'));

                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower()) && logo.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;
                        #region Resize Image
                        string savePath = Server.MapPath("~/Content/images/computers/");

                        Image convertedImage = Image.FromStream(logo.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion
                        if (computer.ComputerPhoto != null && computer.ComputerPhoto != "noImage.png")
                        {
                            string path = Server.MapPath("~/Content/Images/productImages/");
                            ImageUtility.Delete(path, computer.ComputerPhoto);
                        }
                        computer.ComputerPhoto = file;
                    }
                }
                #endregion
                db.Entry(computer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", computer.OwnerId);
            return View(computer);
        }

        // GET: Computers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Computer computer = db.Computers.Find(id);
            if (computer == null)
            {
                return HttpNotFound();
            }
            return View(computer);
        }

        // POST: Computers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Computer computer = db.Computers.Find(id);

            //Delete the image file
            string path = Server.MapPath("~/Content/images/computers/");
            ImageUtility.Delete(path, computer.ComputerPhoto);

            db.Computers.Remove(computer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSWDFinalProject.UI.MVC/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.DATA.EF;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class LocationsController : Controller
    {
        private FinalEntities db = new FinalEntities();

        // GET: Locations
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        #region AJAX CRUD
        //Delete
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AjaxDelete(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();

            string confirmMessage = string.Format("Deleted '{0}' from locations!", location.LocationName);
            return Json(new { id = id, message = confirmMessage });
        }

        //Details
        [HttpGet]
        public PartialViewResult LocationDetails(int id)
        {
            Location location = db.Locations.Find(id);
            return PartialView(location);
        }

        //Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxCreate(Location location)
        {
            db.Locations.Add(location);
            db.SaveChanges();
            return Json(location);
        }

        //Edit - GET
        public PartialViewResult LocationEdit(int id)
        {
            Location location = db.Locations.Find(id);
            return PartialView(location);
        }

        //Edit - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxEdit(Location location)
        {
            db.Entry(location).State = EntityState.Modified;
            db.SaveChanges();
            return Json(location);
        }





        #endregion


        //// GET: Locations/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Location location = db.Locations.Find(id);
        //    if (location == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(location);
        //}

        //// GET: Locations/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Locations/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Locations.Add(location);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(location);
        //}

        //// GET: Locations/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Location location = db.Locations.Find(id);
        //    if (location == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(location);
        //}

        //// POST: Locations/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(location).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(location);
        //}

        //// GET: Locations/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Location location = db.Locations.Find(id);
        //    if (location == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(location);
        //}

        //// POST: Locations/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Location location = db.Locations.Find(id);
        //    db.Locations.Remove(location);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSWDFinalProject.UI.MVC/Views/Shared/_BannerPartial.cshtml
    <!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

        <div class="d-flex justify-content-between align-items-center">
            <h2>@ViewBag.Title</h2>
            <ol>
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li>@ViewBag.Title</li>
            </ol>
        </div>

    </div>
</section>
<!-- End Breadcrumbs -->

FSWDFinalProject.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title> KC Digital | @ViewBag.Title </title>

    <meta content="KC Digital is a personal project built by Edward Barrier III, a Centriq student." name="description">
    <meta content="Edward Barrier III" name="author" />

    <!-- Favicons -->
    <link href="~/Content/assets/img/favicon.png" rel="icon">
    <link href="~/Content/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">


    @* Style bundle *@
    @Styles.Render("~/Content/css")

    @* jQuery UI CSS *@
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">

    @* jQuery script links *@
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    @* Font Awesome CDN *@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">

    @* Render section for AJAX -> located on Locations index. *@
    @RenderSection("htmlHead", required: false)

    <!-- =======================================================
    * Template Name: Sailor - v2.3.1
    * Template URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center">

            <h1 class="logo bx-pull-left">
                <a href="@Url.Action("Index", "Home")">
                    KC Digital <i class="fas fa-laptop"></i>
                </a>
            </h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo"><img src="~/Content/assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav class="nav-menu d-none d-lg-block">

                <ul class="navbar-menu">
                    <li><a href="@Url.Action("Index", "Home")">Home</a></li>

                    @* use the list below for admin functionality *@

                    <li><a href="@Url.Action("Index", "Locations")">Locations</a></li>
                    @if (Request.IsAuthenticated)
                    {
                        <li><a href="@Url.Action("Index", "Computers")">Computers</a></li>
                        <li><a href="@Url.Action("Index", "Reservations")">Reservations</a></li>
                    }
                    <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>

            </nav><!-- .nav-menu -->

            <a href="@Url.Action("Index", "Reservations")" class="get-started-btn">Make a Reservation!</a>

        </div>
    </header><!-- End Header -->
    @RenderBody()
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <h3>KC Digital</h3>
                            <p>
                                4409 E 9th St S <br>
                                Kansas City, MO 64124<br><br>
                                <strong>Phone:</strong> (816) 231-0016<br>
                                <strong>Email:</strong> edwardbarrier@KCDigital.com<br>
                            </p>
                            <div class="social-links mt-3">
                                <a href="https://www.twitter.com/CodeWithEd" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="https://www.linkedin.com/in/edwardbarrieriii/" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                                <a href="https://github.com/Ebarrieriii?tab=repositories" class="github">
                                    <i class="fab fa-github"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Locations")">Locations</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">Make a Reservation</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Contact", "Home")">Contact</a></li>
                        </ul>
                    </div>

                    @if (Request.IsAuthenticated)
                    {
                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Our Services</h4>
                            <ul>
                                <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">File Transfers</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">Computer Diagnostics</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">Screen Replacement</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">Virus Removal</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">Software Help</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a href="@Url.Action("Index", "Reservations")">Hard Drive Repair</a></li>
                            </ul>
                        </div>
                    }

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Edward Barrier III</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/sailor-free-bootstrap-theme/ -->
                Designed by <a href="https://bootstrapmade.com/" target="_blank">BootstrapMade</a> | Converted by <a href="http://edwardbarrier.com/" target="_blank">Edward Barrier III</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    @*Bundle for JavaScript files*@
    @Scripts.Render("~/bundles/template")

    @* Function for targeting current nav link *@
    <script>
        $(function () {
            $('.navbar-menu > li a').each(function () {
                if ($(this).attr('href') == window.location.pathname) {
                    $(this).addClass('active');
                }
            });
        });
    </script>
</body>

</html>

@RenderSection("scripts", required: false)