FSWDFinalProject.UI.MVC/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class ReservationsController : Controller
    {
        private FinalEntities db = new FinalEntities();

        // GET: Reservations
        //Lock down the view so anonymous users can't reach it.
        [Authorize(Roles = "Admin, Customer, Employee")]
        public ActionResult Index()
        {
            //Show only the current users reservations.
            var currentUser = User.Identity.GetUserId();

            if (User.IsInRole("Customer"))
            {
                var reservation = db.Reservations.Where(c => c.Computer.OwnerId == currentUser).Include(c => c.Computer.UserDetail).Include(r => r.Computer).Include(r => r.Location).ToList();

                return View(reservation.ToList());
            }

            var reservations = db.Reservations.Include(r => r.Computer).Include(r => r.Location);
            return View(reservations.ToList());
           
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        public ActionResult Create()
        {
            //Show only the current users assets in the drop down when creating a new reservation.
            var currentUserId = User.Identity.GetUserId();

            ViewBag.ComputerId = new SelectList(db.Computers.Where(o => o.OwnerId == currentUserId), "ComputerId", "ComputerModel");
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationId,ComputerId,LocationId,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                var location = db.Locations.Where(l => l.LocationId == reservation.LocationId).FirstOrDefault();
                //Setting a reservation limit, if the limit is reached, send the user to an error page.
                if (location.Reservations.Where(r => r.ReservationDate == reservation.ReservationDate).ToList().Count >= location.ReservationLimit && !User.IsInRole("Admin"))
                {
                    return RedirectToAction("Error", "Shared");
                }
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            
            ViewBag.ComputerId = new SelectList(db.Computers, "ComputerId", "ComputerModel", reservation.ComputerId);
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName", reservation.LocationId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }

            //Getting only current users computers.
            var currentUserId = User.Identity.GetUserId();

            ViewBag.ComputerId = new SelectList(db.Computers.Where(o => o.OwnerId == currentUserId), "ComputerId", "ComputerModel");
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName", reservation.LocationId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationId,ComputerId,LocationId,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                var location = db.Locations.AsNoTracking().Where(l => l.LocationId == reservation.LocationId).FirstOrDefault();
               
                

                if (location.Reservations.Where(r => r.ReservationDate == reservation.ReservationDate).ToList().Count >= location.ReservationLimit && !User.IsInRole("Admin"))
                {
                    return RedirectToAction("Error", "Shared");
                }

                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ComputerId = new SelectList(db.Computers, "ComputerId", "ComputerModel", reservation.ComputerId);
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName", reservation.LocationId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FSWDFinalProject.UI.MVC/Views/Reservations/Create.cshtml
@model FSWDFinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ComputerId, "Computer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ComputerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ComputerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

        <script type="text/javascript">
            $(document).ready(function () {
                $('input[type=datetime]').datepicker({
                    dateFormat: "dd/M/yy",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0"
                });

            });
        </script>
    }

FSWDFinalProject.UI.MVC/Views/Reservations/Delete.cshtml
@model FSWDFinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Computer.ComputerModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Computer.ComputerModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FSWDFinalProject.UI.MVC/Views/Reservations/Details.cshtml
@model FSWDFinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Computer.ComputerModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Computer.ComputerModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ReservationId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FSWDFinalProject.UI.MVC/Views/Reservations/Edit.cshtml
@model FSWDFinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReservationId)

        <div class="form-group">
            @Html.LabelFor(model => model.ComputerId, "ComputerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ComputerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ComputerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSWDFinalProject.UI.MVC/Views/Reservations/Index.cshtml
@model IEnumerable<FSWDFinalProject.DATA.EF.Reservation>

@{
    ViewBag.Title = "My Reservations";
}

@Html.Partial("_BannerPartial")

<p>
    @*@Html.ActionLink("Make a Reservation!", "Create", null, new { @class = "ml-4" })*@
    <a class="btn btn-primary ml-4 mt-3" href="@Url.Action("Create", "Reservations")">Add New <i class="fas fa-plus"></i></a>

</p>
<table class="table ml-3 data-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Computer.ComputerModel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.LocationName)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ReservationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Computer.ComputerModel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.LocationName)
                </td>
                <td>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Customer"))
                    {
                        <a href="@Url.Action("Edit", "Reservations", new {id = item.ReservationId})"><i class="fas fa-edit"></i></a>
                        <br/>
                        <a href="@Url.Action("Details", "Reservations", new { id=item.ReservationId})"> <i class="fas fa-info-circle"></i></a>
                        <br/>
                        <a href="@Url.Action("Delete", "Reservations", new {id = item.ReservationId})"><i class="fas fa-trash-alt"></i></a>
                    }
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts {
    <script>
        //Apply the jQuery plugin function
        $(document).ready(function () {
            $(".data-table").DataTable();
        });
    </script>
}